name = "ruqola"
version = "0.1.0"
defaultTargets = ["ruqola"]

[[lean_lib]]
name = "Ruqola"

[[lean_exe]]
name = "ruqola"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[require]]
name = "REPL"
git = "https://github.com/leanprover-community/repl"
